package boardLogic;

import fieldLogic.Field;

public class BoardFields {
    public static Field[] getFields(float boardX, float boardY, float boardLength) {
        return new Field[]{
                new Field(1, boardX + (boardLength / 1.13f), boardLength / 15),
                new Field(2, boardX + (boardLength / 14f), boardLength / 8.5f),
                new Field(3, 0, 0),
                new Field(4, 0, 0),
                new Field(5, boardX + (boardLength / 1.22f), boardLength / 23),
                new Field(6, boardX + (boardLength / 1.33f), boardLength / 19),
                new Field(7, boardX + (boardLength / 1.45f), boardLength / 12),
                new Field(8, boardX + (boardLength / 1.54f), boardLength / 7),
                new Field(9, boardX + (boardLength / 1.56f), boardLength / 5),
                new Field(10, boardX + (boardLength / 1.71f), boardLength / 5),
                new Field(11, boardX + (boardLength / 2f), boardLength / 5),
                new Field(12, boardX + (boardLength / 2.43f), boardLength / 5),
                new Field(13, boardX + (boardLength / 2.83f), boardLength / 5),
                new Field(14, boardX + (boardLength / 2.90f), boardLength / 7),
                new Field(15, boardX + (boardLength / 3.33f), boardLength / 12),
                new Field(16, boardX + (boardLength / 4f), boardLength / 19),
                new Field(17, boardX + (boardLength / 5.5f), boardLength / 23),
                new Field(18, boardX + (boardLength / 9f), boardLength / 15),
                new Field(19, boardX + (boardLength / 22f), boardLength / 5.5f),
                new Field(20, boardX + (boardLength / 20f), boardLength / 4f),
                new Field(21, boardX + (boardLength / 13f), boardLength / 3.3f),
                new Field(22, 0, 0),
                new Field(23, 0, 0),
                new Field(24, 0, 0),
                new Field(25, 0, 0),
                new Field(26, 0, 0),
                new Field(27, 0, 0),
                new Field(28, 0, 0),
                new Field(29, 0, 0),
                new Field(30, 0, 0),
                new Field(31, 0, 0),
                new Field(32, 0, 0),
                new Field(33, 0, 0),
                new Field(34, 0, 0),
                new Field(35, 0, 0),
                new Field(36, 0, 0),
                new Field(37, 0, 0),
                new Field(38, 0, 0),
                new Field(39, 0, 0),
                new Field(40, 0, 0),
                new Field(41, 0, 0),
                new Field(42, 0, 0),
                new Field(43, 0, 0),
                new Field(44, 0, 0),
                new Field(45, 0, 0),
                new Field(46, 0, 0),
                new Field(47, 0, 0),
                new Field(48, 0, 0),
                new Field(49, 0, 0),
                new Field(50, 0, 0),
                new Field(51, 0, 0),
                new Field(52, 0, 0),
                new Field(53, 0, 0),
                new Field(54, 0, 0),
                new Field(55, 0, 0),
                new Field(56, 0, 0),
                new Field(57, 0, 0),
                new Field(58, 0, 0),
                new Field(59, 0, 0),
                new Field(60, 0, 0),
                new Field(61, 0, 0),
                new Field(62, 0, 0),
                new Field(63, 0, 0),
                new Field(64, 0, 0),
                new Field(65, 0, 0),
                new Field(66, 0, 0),
                new Field(67, 0, 0),
                new Field(68, 0, 0),
                new Field(69, 0, 0),
                new Field(70, 0, 0)
        };
    }
}
